### ISSUE TITLE
[WIP] Re-design Godot 4 VS2022 Extension

### ISSUE THREAD

**Issue by GeorgeS2019** [godotengine/godot-csharp-visualstudio#49]
@akien-mga
## Why updating Godot 4 VS2022 Extension is important?
Many Godot 4 industry partners specifically specify keeping the Godot 4 for .NET up-to-date.

## Suggestions
- Launch
- Play in Editor
- Launch (Select Scene)
- Attach

If it is Godot4 for .NET, when the Visual Studio 2022 solution project is created, the default debugging profile will be replaced with the executable profiles listed above 

The instructions for creating the executable profiles have been discussed [here](https://github.com/godotengine/godot-csharp-visualstudio/issues/48).

Do add/contribute further suggestions and improvements to the Godot 4 VS2022 Extension 

- [ ] [Implement Input map suggestion](https://github.com/godotengine/godot-csharp-visualstudio/issues/46)
- [ ] [Godot would set an environment variable for the Godot Executable used](https://github.com/godotengine/godot-csharp-visualstudio/issues/45#issuecomment-1312712533)
- [ ] [Enhancement of GD.Print](https://gist.github.com/SilentPenguin/bf24eb348c9d00c34605d1cc54318be7) 
- [ ] Automated update the list of Scenes in Godot Project to support [Launch (Select Scene)](https://github.com/godotengine/godot-csharp-visualstudio/issues/9)
- [ ] Many open issues here are no longer valid with the new .NET6/7 for Godot4 

#### Optional for further discussion
- [ ] Support Godot 4 NUnit unit testing within VS2022
- [ ] Support Godot 4 XUnit unit testing within VS2022

### Reference [VS Code: C# Tools for Godot](https://github.com/godotengine/godot-csharp-vscode)

<details>
<summary><strong>VS Code: Debugger launch configurations</summary>

## Debugger launch configurations

By default the extension creates the following launch configurations:

- **Play in Editor**\
  Launches the game in the Godot editor for debugging in VSCode.\
  For this option to work, a running Godot instance must be editing the project.
- **Launch**\
  Launches the game with a Godot executable for debugging in VSCode.\
  This option requires the value of the _"executable"_ property to be set to
  a path that points to the Godot executable that will be launched.\
  The `godot.csharp.executablePath` setting can be configured to automatically populate the
  executable property with its value, if not configured it will be populated with the path
  to the running Godot instance if there is one, otherwise it will have to be populated manually.
  See [additional `Launch` configuration](#additional-launch-configuration).
- **Launch (Select Scene)**\
  Launches the game with a Godot executable for debugging in VSCode, allowing the user
  to select which scene to run on every execution.\
  This option works just like the `Launch` option and also requires the value
  of the _"executable"_ property to be set.
  See [additional `Launch` configuration](#additional-launch-configuration).
- **Attach**\
  Attaches to a running Godot instance that was configured to listen for a debugger connection.

</details>

**Comment by GeorgeS2019** [comment]
FYI:
@Xyotic
@paiden
@Perndoe

**Comment by Xyotic** [comment]
I guess it might be possible to add "Launch (Select Scene)" via a launchSettings.json...
Maybe the extention could generate the launch profiles everytime a new scene file gets created/deleted inside the project?
We could use [FileSystemWatcher](https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-7.0) for this.

**Comment by GeorgeS2019** [comment]
@Xyotic 
With .NET6 and Godot4, VS2022 is becoming less challenging to configure LIKE VS Code.

The extension first milestones is to automate as u have suggested. :-)

**Comment by GeorgeS2019** [comment]
```json
{
  "profiles": {
    "Editor": {
      "commandName": "Executable",
      "executablePath": "Path to Godot_v4.1-rc2_mono_win64\\Godot_v4.1-rc2_mono_win64.exe",
      "commandLineArgs": "--path . --editor --verbose",
      "workingDirectory": ".",
      "nativeDebugging": true
    },
    "Launch": {
      "commandName": "Executable",
      "executablePath": "Path to Godot_v4.1-rc2_mono_win64\\Godot_v4.1-rc2_mono_win64.exe",
      "commandLineArgs": "--path . --verbose",
      "workingDirectory": ".",
      "nativeDebugging": true
    }
  }
}
```
